language: node_js
node_js:
  - "iojs"
  - "7"
  install:
  - npm install;
    npm install travis-github-lint-status;
script:
  - npm run lint
  - npm run build
  - npm test
after_script:
- "npm run test:cov"
- "npm install coveralls && cat ./coverage/lcov.info | coveralls"
