language: node_js
node_js:
  - "iojs"
  - "7"
script:
  - npm run lint
  - npm run build
  - npm test
after_script:
- "npm run test:cov"
- "npm install coveralls && cat ./coverage/lcov.info | coveralls"

