language: node_js
node_js:
  - "iojs"
  - "7"
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
cache:
  directories:
    - node_modules
sudo: false
after_script:
- "npm run test:cov"
- "npm install coveralls && cat ./coverage/lcov.info | coveralls"
- "npm install monaco-editor"



